### ISSUE TITLE
Page not fully loaded in report

### ISSUE THREAD

**Issue by himynameistim** [netlify/netlify-plugin-lighthouse#585]
**Describe the bug**
The lighthouse report in Netlify is showing good scores compared to running a lighthouse report on the actual website. When viewing the report I can see it's because the page hasn't loaded the sites stylesheet (no way to tell is anything else hadn't loaded).

**Expected behavior**
Expect results to match production version of the site

**Screenshots**
<img width="518" alt="image" src="https://github.com/netlify/netlify-plugin-lighthouse/assets/5212530/7510da74-a95e-4a2a-8cd8-828636f27a6a">

**Additional context**
Plugin was installed through Netlify and no config has been changed

**Comment by aitchiss** [comment]
Hi @himynameistim 👋 

Thank you for logging this issue. We just shipped version 5.0.0 of the plugin, which makes a key change that should correct the behaviour you have noted. As of this release, by default we'll run the lighthouse audit against the live deploy URL (rather than a statically served version of your site). This means all of your assets should be in place as expected.

Please try upgrading, and if you still have difficulties, feel free to re-open the issue!
